name: restaurants
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2
  collection: ^1.16.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.1.1
  font_awesome_flutter: ^10.2.1
  go_router: ^5.2.0
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  http: ^0.13.5
  intl: ^0.17.0
  lottie: ^2.0.0
  mobile_scanner: ^2.1.0
  riverpod: ^2.1.1
  socket_io_client: ^2.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
