name: diner
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^2.1.0
  uuid: ^3.0.7
  oyt_front_core:
    path: ./packages/oyt_front_core
  oyt_front_widgets:
    path: ./packages/oyt_front_widgets
  oyt_front_auth:
    path: ./packages/oyt_front_auth
  oyt_front_restaurant:
    path: ./packages/oyt_front_restaurant
  oyt_front_product:
    path: ./packages/oyt_front_product
  oyt_front_order:
    path: ./packages/oyt_front_order
  oyt_front_table:
    path: ./packages/oyt_front_table
  oyt_front_menu:
    path: ./packages/oyt_front_menu

dev_dependencies:
  dart_code_metrics: ^5.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
