name: restaurants
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.1.1
  font_awesome_flutter: ^10.3.0
  go_router: ^5.2.2
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  lottie: ^2.0.0
  mobile_scanner: ^2.1.0
  riverpod: ^2.1.1
  uuid: ^3.0.7
  oyt_front_core:
    path: ./packages/oyt_front_core
  oyt_front_widgets:
    path: ./packages/oyt_front_widgets
  oyt_front_auth:
    path: ./packages/oyt_front_auth
  oyt_front_restaurant:
    path: ./packages/oyt_front_restaurant
  oyt_front_product:
    path: ./packages/oyt_front_product
  oyt_front_order:
    path: ./packages/oyt_front_order
  oyt_front_table:
    path: ./packages/oyt_front_table

dev_dependencies:
  dart_code_metrics: ^5.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
